name: CI/CD

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  success:
    strategy:
      matrix:
        os: [ windows-2022, macos-14, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2
      - name: Create staging repository
        id: create-staging-repo
        uses: ./
        with:
          group-id: org.danilopianini
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      - shell: bash
        run: '[ -z "${{ steps.create-staging-repo.outputs.staging-repo-id }}" ] && exit 1 || echo "OK"'
      - name: Drop staging repository
        uses: danysk/action-drop-ossrh-staging-repo@1.0.3
        with:
          repo-id: ${{ steps.create-staging-repo.outputs.staging-repo-id }}
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      - name: Install Node
        uses: actions/setup-node@v4.3.0
        if: runner.os == 'linux'
        with:
          node-version-file: package.json
      - run: npm install
        if: runner.os == 'linux'
      - run: npx semantic-release
        if: runner.os == 'linux'
        env:
          GITHUB_TOKEN: ${{ github.token }}
